### ISSUE TITLE
if the main project changes when running a test, the test jar should also be deleted

### ISSUE THREAD

**Issue by fommil** [fommil/sbt-big-project#42]

**Comment by vovapolu** [comment]
`allPackagesBin` has ```
p <- proj +: { if (skipEclipseMain) Nil else ((eclipseTestsFor in proj) get structure.data).get.toSeq }
```
but `outdatedPackageBins` has 
```
p <- proj +: ((eclipseTestsFor in proj) get structure.data).get.toSeq
```

**Comment by fommil** [comment]
I think I hit a race condition, easily done with mutable text editors.
